### PR TITLE
packages: Fix build from branch/commit ID

### LINKED ISSUE #124: Building from a commit replaces version
When building from a specific branch or commit, the version gets replaced in the templates, so the OBS _service file will know from where retrieve a source tarball. The problem is that all the VERSION string gets replaced in the remaining templates so  a package gets created with a wrong version number. example: `cc-proxy-28b5af4+git.28b5af4-6.1`. In this case the version got replaced by the short form of the commit ID.

### PR DESCRIPTION
**Pull request by erick0z**
This commit fixes the behaviour when building from a commit ID.
It now correctly replaces version strings and commit IDs.

Fixes #124

### CODE REVIEW

File: proxy/update_proxy.sh [hunk 1]
```diff
@@ -66,13 +73,7 @@ sed -e "s/@VERSION@/$VERSION/g" \
...
 sed -e "s/@VERSION@/$VERSION/g" debian.control-template > debian.control
 
-if [ -z "$ORIGINAL_VERSION" ]; then
-    sed "s/@VERSION@/$VERSION/g;" _service-template > _service
-else
-    sed "s/@VERSION@/$ORIGINAL_VERSION/g;" _service-template > _service
-fi
-
-[ -n "$1" ] && sed -e "s/@PARENT_TAG@/$VERSION/" -i _service || :
+[ -n "$1" ] && sed "s/@REVISION@/$OBS_REVISION/" _service-template > _service || sed "s/@REVISION@/$VERSION/"  _service-template > _service
```
Comment (gorozco1) [inline proxy/update_proxy.sh]: Add an explanation here in a comment, why we are using two variables to replace the same value.

**Review by gorozco1 — APPROVED** [review]
lgtm in general. just a minor change requested.

File: proxy/update_proxy.sh (hunk 1 above)
Comment (erick0z) [reply proxy/update_proxy.sh]: @gorozco1 Done

**Review by gorozco1 — APPROVED** [review]
