### PR TITLE
kernel: fix dependency conflict (libelf-devel)

### LINKED ISSUE #280: kernel: Dependecy conflict in the specfile
There is a conflict of dependencies for the `libelf-devel` package for RPM distros (RHEL, CentOS, Fedora, SUSE). A proper handling of this dependency must be added.

### PR DESCRIPTION
**Pull request by erick0z**
There is a conflict of dependencies for the libelf-devel package for RPM distros
(RHEL, CentOS, Fedora, SUSE). A proper handling of this dependency must be added.
This patch fixes the dependency conflict.

Fixes #280

### CODE REVIEW

File: kernel/update_kernel.sh [hunk 1]
```diff
@@ -26,7 +26,7 @@ KR_REL=https://www.kernel.org/releases.json
 KR_SHA=https://cdn.kernel.org/pub/linux/kernel/v"${KR_SERIES}"/sha256sums.asc
 
 GENERATED_FILES=(linux-container.dsc linux-container.spec _service config)
-STATIC_FILES=(debian.dirs debian.rules debian.compat debian.control debian.copyright)
+STATIC_FILES=(debian.dirs debian.rules debian.compat debian.control debian.copyright debian.series)
```
Comment (jodh-intel) [inline kernel/update_kernel.sh]: I don't understand why this is on the same commit? If it's not strictly related to the libelf change, could you add a separate commit for this change please?

**Review by jodh-intel — COMMENTED** [review]
Just one comment about the `update_kernel.sh` change.

File: kernel/update_kernel.sh (hunk 1 above)
Comment (erick0z) [reply kernel/update_kernel.sh]: @jodh-intel Sure, I will send another PR for that, my bad. That's a missing change that I forgot to ask in the previous kernel PR, as it was merged.

Comment (jodh-intel) [reply kernel/update_kernel.sh]: No probs, and thanks ;)

**Comment by jodh-intel** [comment]
lgtm

**Comment by jcvenegas** [comment]
lgtm

**Review by jcvenegas — APPROVED** [review]

**Comment by devimc** [comment]
LGTM
