### PR TITLE
release-tools: use sudo to create rootfs and image

### LINKED ISSUE #276: release_image_github.sh should call make rootfs and make image using sudo.
`release_image_github.sh` calls `make rootfs` and `make image`, but it should be called using sudo as if the user has not access to the docker socket, the script will fail

### PR DESCRIPTION
**Pull request by chavafg**
If a user does not have access to docker,
release_image_github.sh will fail.
This commit adds sudo to the make rootfs and make
image calls (which use docker) in the
release_image_github.sh script

Fixes: #276.

Signed-off-by: Salvador Fuentes <salvador.fuentes@intel.com>

### CODE REVIEW

File: release-tools/release_image_github.sh [hunk 1]
```diff
@@ -58,8 +58,8 @@ build_image() {
 	export USE_DOCKER=1
 	export WORKDIR="${workdir_builder}"
 
-	AGENT_VERSION="${agent_version}" OS_VERSION="${os_version}" make rootfs
-	make image
+	AGENT_VERSION="${agent_version}" OS_VERSION="${os_version}" sudo make rootfs
```
Comment (jodh-intel) [inline release-tools/release_image_github.sh]: Shouldn't this be `sudo -E`?

Comment (chavafg) [reply release-tools/release_image_github.sh]: right, fixed :)

**Review by jodh-intel — APPROVED** [review]
lgtm
