### PR TITLE
packages: Fix OBS build from hash

### LINKED ISSUE #66: Fix OBS build from hash
When building from hash in OBS, if the first character of the hash starts with a letter, it will fail to build since a number is expected.

### PR DESCRIPTION
**Pull request by erick0z**
This commit fixes the problem when a build from master fails
because the hash starts with a letter. It substitutes the first
letter for a "1".

Fixes #66

### CODE REVIEW

File: proxy/update_proxy.sh [hunk 1]
```diff
@@ -47,7 +52,12 @@ changelog_update $VERSION
 sed -e "s/@VERSION@/$VERSION/" cc-proxy.spec-template > cc-proxy.spec
 sed -e "s/@VERSION_DEB_TRANSFORM@/$VERSION_DEB_TRANSFORM/g;" -e "s/@HASH_TAG@/$short_hashtag/g;" cc-proxy.dsc-template > cc-proxy.dsc
 sed -e "s/@VERSION_DEB_TRANSFORM@/$VERSION_DEB_TRANSFORM/g;" -e "s/@HASH_TAG@/$short_hashtag/g;" debian.control-template > debian.control
-sed "s/@VERSION@/$VERSION/g;" _service-template > _service
+
+if [ -z $ORIGINAL_VERSION ]; then
```
Comment (gorozco1) [inline proxy/update_proxy.sh]: if [ -z "$ORIGINAL_VERSION" ]; then

File: runtime/update_runtime.sh [hunk 2]
```diff
@@ -70,7 +75,11 @@ function templating_non_staging(){
         -e "s/@qemu_lite_version@/$qemu_lite_obs_ubuntu_version/" \
         -e "s/@linux_container_version@/$linux_container_obs_ubuntu_version/" debian.control-template > debian.control
 
-    sed "s/@VERSION@/$VERSION/g;" _service-template > _service
+    if [ -z $ORIGINAL_VERSION ]; then
```
Comment (gorozco1) [inline runtime/update_runtime.sh]: if [ -z "$ORIGINAL_VERSION" ]; then

File: runtime/update_runtime.sh [hunk 3]
```diff
@@ -85,7 +94,11 @@ function templating_staging(){
     sed -e "s/@VERSION_DEB_TRANSFORM@/$VERSION_DEB_TRANSFORM/g;" \
         -e "s/@HASH_TAG@/$short_hashtag/g;" debian.control-template > debian.control
 
-    sed "s/@VERSION@/$VERSION/g;" _service-template > _service
+    if [ -z $ORIGINAL_VERSION ]; then
```
Comment (gorozco1) [inline runtime/update_runtime.sh]: if [ -z "$ORIGINAL_VERSION" ]; then

File: shim/update_shim.sh [hunk 4]
```diff
@@ -48,7 +53,14 @@ changelog_update $VERSION
 sed "s/@VERSION@/$VERSION/g;" cc-shim.spec-template > cc-shim.spec
 sed -e "s/@VERSION_DEB_TRANSFORM@/$VERSION_DEB_TRANSFORM/g;" -e "s/@HASH_TAG@/$short_hashtag/g;" cc-shim.dsc-template > cc-shim.dsc
 sed -e "s/@VERSION_DEB_TRANSFORM@/$VERSION_DEB_TRANSFORM/g;" -e "s/@HASH_TAG@/$short_hashtag/g;" debian.control-template > debian.control
-sed "s/@VERSION@/$VERSION/g;" _service-template > _service
+
+if [ -z $ORIGINAL_VERSION ]; then
```
Comment (gorozco1) [inline shim/update_shim.sh]: if [ -z "$ORIGINAL_VERSION" ]; then

**Review by gorozco1 — CHANGES_REQUESTED** [review]
In general lgtm needed "" in a conditional

**Review by gorozco1 — APPROVED** [review]
