### PR TITLE
runtime: Fix dependencies for staging repo

### LINKED ISSUE #56: fedora: dnf install cc-runtime does not installs cc-runtime-bin neither cc-runtime-config packages
On Fedora, when trying to install `cc-runtime` package, it will not download the packages that really matter, which are `cc-runtime-bin` and `cc-runtime-config`. You need to specify to `dnf` to install the 3 packages. 
`cc-runtime-bin` and `cc-runtime-config` should be installed as dependencies of `cc-runtime` package

```
[cloud@fedora26-obs-cc3 ~]$ sudo dnf install cc-runtime
Last metadata expiration check: 0:19:30 ago on Mon 14 Aug 2017 10:01:19 AM UTC.
Dependencies resolved.
==================================================================================================
 Package    Arch   Version                  Repository                                       Size
==================================================================================================
Installing:
 cc-runtime x86_64 5dea7cb+git.5dea7cb-69.1 home_clearcontainers_clear-containers-3-staging 6.6 k

Transaction Summary
==================================================================================================
Install  1 Package

Total download size: 6.6 k
Installed size: 0
```

### PR DESCRIPTION
**Pull request by erick0z**
Due to a wrong substitution/deletion of requirements, the meta
package (cc-runtime) does not retrieve the content packages
(cc-runtime-bin and cc-runtime-conf). This commit fixes the
sed command with a proper substitution. This also fixes a
missing sed command that replaces the qemu version.

Fixes #56

### CODE REVIEW

**Review by gorozco1 — APPROVED** [review]

File: runtime/update_runtime.sh [hunk 1]
```diff
@@ -88,11 +90,12 @@ function templating_staging(){
 
     sed "s/@VERSION@/$VERSION/g;" _service-template > _service
 
-    sed -e "s/^Depends:.*/Depends: \${shlibs:Depends}, \${misc:Depends}, \${perl:Depends}/" \
+    sed -e '/^Package: cc-runtime$/{n;n;s/^Depends: .*/Depends: \${shlibs:Depends}, \${misc:Depends}, \${perl:Depends}, cc-runtime-bin, cc-runtime-config/}' \
         -e "/clear-containers-image*/d" \
         -e "/cc-proxy*/d" -i cc-runtime.dsc debian.control
 
-    sed -e '/Requires: cc-*/d' \
+    sed -e '/Requires: cc-proxy/d' \
```
Comment (gorozco1) [inline runtime/update_runtime.sh:97]: no -bin nor -config required?

**Comment by gorozco1** [comment]
@chavafg please review the dependencies for this PR

File: runtime/update_runtime.sh (hunk 1 above)
Comment (erick0z) [reply runtime/update_runtime.sh:97]: These lines are for removal. So *-bin and *-config will remain.
